### ISSUE TITLE
RoboSat.pink v0.3.0 RoadMap 

### ISSUE THREAD

**Issue by datapink** [datapink/robosat.pink#1]
Plug and play extensible design
- [ ] losses
- [ ] metrics
- [ ] models
- [ ] pretrained model

MultiBands
- [ ] Predict with several inputs
- [ ] Allow PostGIS input
- [ ] Train Freeze layer in userland

MultiClass (as N binary outputs)
- [ ] Train / model
- [ ] Rasterize
- [ ] Predict
- [ ] Config file
- [ ] Auto-Weighted QoD Metrics ?

PyTorch 1.0 / Cuda 10
- [ ] FP16
- [ ] JIT 
- [ ] Update Doc 

Maintenance
- [ ] Tile2GeoJson function
- [ ] no bare except (cf flake8)  
- [ ] fix map_location model stuff
